// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: lib/proto/api/annotations.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RusService with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RusService) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RusService with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RusServiceMultiError, or
// nil if none found.
func (m *RusService) ValidateAll() error {
	return m.validate(true)
}

func (m *RusService) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Kind

	if len(errors) > 0 {
		return RusServiceMultiError(errors)
	}

	return nil
}

// RusServiceMultiError is an error wrapping multiple validation errors
// returned by RusService.ValidateAll() if the designated constraints aren't met.
type RusServiceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RusServiceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RusServiceMultiError) AllErrors() []error { return m }

// RusServiceValidationError is the validation error returned by
// RusService.Validate if the designated constraints aren't met.
type RusServiceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RusServiceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RusServiceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RusServiceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RusServiceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RusServiceValidationError) ErrorName() string { return "RusServiceValidationError" }

// Error satisfies the builtin error interface
func (e RusServiceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRusService.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RusServiceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RusServiceValidationError{}

// Validate checks the field values on Authz with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Authz) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Authz with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AuthzMultiError, or nil if none found.
func (m *Authz) ValidateAll() error {
	return m.validate(true)
}

func (m *Authz) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AnyAuthenticated

	// no validation rules for NamespacePermission

	// no validation rules for OrganisationPermission

	if len(errors) > 0 {
		return AuthzMultiError(errors)
	}

	return nil
}

// AuthzMultiError is an error wrapping multiple validation errors returned by
// Authz.ValidateAll() if the designated constraints aren't met.
type AuthzMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthzMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthzMultiError) AllErrors() []error { return m }

// AuthzValidationError is the validation error returned by Authz.Validate if
// the designated constraints aren't met.
type AuthzValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthzValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthzValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthzValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthzValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthzValidationError) ErrorName() string { return "AuthzValidationError" }

// Error satisfies the builtin error interface
func (e AuthzValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthz.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthzValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthzValidationError{}

// Validate checks the field values on RusMethod with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RusMethod) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RusMethod with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RusMethodMultiError, or nil
// if none found.
func (m *RusMethod) ValidateAll() error {
	return m.validate(true)
}

func (m *RusMethod) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Method

	if all {
		switch v := interface{}(m.GetAuthz()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RusMethodValidationError{
					field:  "Authz",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RusMethodValidationError{
					field:  "Authz",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthz()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RusMethodValidationError{
				field:  "Authz",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RusMethodMultiError(errors)
	}

	return nil
}

// RusMethodMultiError is an error wrapping multiple validation errors returned
// by RusMethod.ValidateAll() if the designated constraints aren't met.
type RusMethodMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RusMethodMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RusMethodMultiError) AllErrors() []error { return m }

// RusMethodValidationError is the validation error returned by
// RusMethod.Validate if the designated constraints aren't met.
type RusMethodValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RusMethodValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RusMethodValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RusMethodValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RusMethodValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RusMethodValidationError) ErrorName() string { return "RusMethodValidationError" }

// Error satisfies the builtin error interface
func (e RusMethodValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRusMethod.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RusMethodValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RusMethodValidationError{}

// Validate checks the field values on RusMessage with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RusMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RusMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RusMessageMultiError, or
// nil if none found.
func (m *RusMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *RusMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for CollectionItself

	if len(errors) > 0 {
		return RusMessageMultiError(errors)
	}

	return nil
}

// RusMessageMultiError is an error wrapping multiple validation errors
// returned by RusMessage.ValidateAll() if the designated constraints aren't met.
type RusMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RusMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RusMessageMultiError) AllErrors() []error { return m }

// RusMessageValidationError is the validation error returned by
// RusMessage.Validate if the designated constraints aren't met.
type RusMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RusMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RusMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RusMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RusMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RusMessageValidationError) ErrorName() string { return "RusMessageValidationError" }

// Error satisfies the builtin error interface
func (e RusMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRusMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RusMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RusMessageValidationError{}
